### ISSUE TITLE
Scripts hangs if a tracker goes down for a short time

### ISSUE THREAD

**Issue by Drazzilb08** [BreadedChickenator/Cross-Seed-AutoDL#13]
Well it seems too have moved past the spot. However, new issue. 
```
Traceback (most recent call last):
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 384, in
main()
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 355, in main
matching_results = searcher.search(local_release_data, search_history)
File "/mnt/user/data/scripts/cross-seed/CrossSeedAutoDL.py", line 115, in search
resp = requests.get(search_url, local_release_data)
File "/usr/lib64/python3.9/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib64/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/lib64/python3.9/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.200', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey=<api>&Query=My+Little+Pony&Tracker%5B%5D=beyond-hd-oneurl%2Canimebytes%2Cbroadcasthenet&Category%5B%5D=5000&season=2&main_path=%2Fmnt%2Fuser%2Fdata%2F.torrents%2Fseries%2FMy+Little+Pony+-+Friendship+Is+Magic+S02+1080p+Netflix+WEB-DL+DD%2B+5.1+x264-TrollHD&basename=My+Little+Pony+-+Friendship+Is+Magic+S02+1080p+Netflix+WEB-DL+DD%2B+5.1+x264-TrollHD&size=19062244781&guessed_data=title&guessed_data=alternative_title&guessed_data=season&guessed_data=screen_size&guessed_data=streaming_service&guessed_data=source&guessed_data=audio_codec&guessed_data=audio_channels&guessed_data=video_codec&guessed_data=release_group&guessed_data=type (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
```

Seems like it occurs when one of the trackers goes down for a moment or two on Jackett. What makes this a bigger issue is that I have over 5,000 torrents in my. folder and the odds of a tracker going down or having some sort of hiccup between it and Jackett goes up considering the amount of time it takes to go through all 5,000+ (especially the first time or with history ignored).

I guess I can roll a feature request in to this. Is there a way to have a config file that we can input the Torznab link into it (along with Jackett API and IP address) so that we aren't using the `/all` end point? Just an idea.

**Comment by BC44** [comment]
I'll look into this.

As far as using the particular torznab link that's in Jackett, it seems that's just an rss url, not one that can be used to conduct a specific search

**Comment by BC44** [comment]
Added some checks in 44f16013006735afa3fdfaa25999e30ea9a89285. Hope it resolves your issue

**Comment by Drazzilb08** [comment]
Thank you for the update. Everything appears to be working fine. I'll consider this closed.
