### ISSUE TITLE
If magnet is not supported, please allow us to skip it and continue on instead of exiting

### ISSUE THREAD

**Issue by newadventure079** [BreadedChickenator/Cross-Seed-AutoDL#20]
It would be nice if the script continued on so it doesn't die if it encounters a magnet link

```
3 matched of 17 results.
- Grabbing release: [PassThePopcorn] 1932_The Death Kiss
- Grabbing release: [ETTV] The Death Kiss (1932) DVD5 Untouched - Bela Lugosi [DDR]
Traceback (most recent call last):
  File "/volume1/homes/scripts/Cross-Seed-AutoDL-master/CrossSeedAutoDL.py", line 430, in <module>
    main()
  File "/volume1/homes/scripts/Cross-Seed-AutoDL-master/CrossSeedAutoDL.py", line 390, in main
    Downloader.download(result, search_history)
  File "/volume1/homes/scripts/Cross-Seed-AutoDL-master/CrossSeedAutoDL.py", line 257, in download
    response = requests.get(result['Link'], stream=True)
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/var/services/homes/.local/lib/python3.9/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:223a06d7680ec8c544ef124a6a8050b98919d08f&dn=The+Death+Kiss+%281932%29+DVD5+Untouched+-+Bela+Lugosi+%5BDDR%5D&xl=0&tr=http%3A%2F%2Ftracker.aletorrenty.pl:2710/announce&tr=udp%3A%2F%2F178.33.73.26:2710/announce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org:6969/announce&tr=udp%3A%2F%2Ftracker.mg64.net:6969/announce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk:6969/announce&tr=udp%3A%2F%2Fopen.demonii.com:1337/announce&tr=udp%3A%2F%2Ftracker.internetwarriors.net:1337/announce&tr=udp%3A%2F%2F9.rarbg.me:2750/announce&tr=udp%3A%2F%2Ftracker.ex.ua:80/announce&tr=udp%3A%2F%2Fpow7.com:80/announce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu:80/announce&tr=udp%3A%2F%2Ftracker.openbittorrent.com/announce&tr=udp%3A%2F%2Fexodus.desync.com:6969/announce&tr=udp%3A%2F%2F11.rarbg.com/announce'

```

**Comment by BC44** [comment]
fixed in a8dcf9ae06d9dcd0c0e8dec18091cb4445f6ddc3

Will now create `.url` shortcuts with magnet links
