### ISSUE TITLE
Search keeps randomly stopping

### ISSUE THREAD

**Issue by Fiala06** [BreadedChickenator/Cross-Seed-AutoDL#8]
I keep having an issue trying to run this. This last run I got to 179 out of 1349. It just stops with the following error:

```
Searching for 179 of 1349:      ['Jr Jr Good Old Days 2020']    ['Jr Jr - Good Old Days (2020) [WEB FLAC]', 23962301]

Traceback (most recent call last):
  File "CrossSeedAutoDL.py", line 235, in <module>
    main()
  File "CrossSeedAutoDL.py", line 99, in main
    returnedJSON = json.loads(source)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Any ideas what the cause could be? I'm running this on a seedbox Debian 10 and Python v3.7.3 Thanks!

**Comment by BC44** [comment]
New code should power through the search. I've introduced logging in case the issue props up again for you.
