### ISSUE TITLE
Long paths causing crash

### ISSUE THREAD

**Issue by guytanium** [BreadedChickenator/Cross-Seed-AutoDL#9]
Hi, whenever the tool attempts to search a longer than normal path l I get a crash. I'm using shared network folders, if it matters. Ideally it shouldn't end the process but instead could just skip it.
Example:
```{}
Traceback (most recent call last):
  File "CrossSeedAutoDL.py", line 235, in <module>
    main()
  File "CrossSeedAutoDL.py", line 73, in main
    pathSize = get_size(path)
  File "CrossSeedAutoDL.py", line 130, in get_size
    filesize = get_file_size(os.path.join(root, filename))
  File "CrossSeedAutoDL.py", line 139, in get_file_size
    targetPath = os.readlink(filepath)
FileNotFoundError: [WinError 3] The system cannot find the path specified: "\\\\nas\\TV-Shows\\Its Always Sunny in Philadelphia\\Its.Always.Sunny.In.Philadelphia.S09.720p.WEB-DL.AAC2.0.H.264-BS\\It's.Always.Sunny.In.Philadelphia.S09.720p.WEB-DL.AAC2.0.H.264-BS\\It's.Always.Sunny.In.Philadelphia.S09E01.The.Gang.Broke.Dee.720p.WEB-DL.AAC2.0.H.264-BS.mkv"

**Comment by BC44** [comment]
A small fix was added in 9382845fb97ed0c27886e6777d947b456d46c081. Let me know if there's still an issue
